---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - jk.jk.com
  resources:
  - myapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - jk.jk.com
  resources:
  - myapps/finalizers
  verbs:
  - update
- apiGroups:
  - jk.jk.com
  resources:
  - myapps/status
  verbs:
  - get
  - patch
  - update
